"""empty message

Revision ID: 8326e338d55b
Revises: 
Create Date: 2019-12-14 09:37:57.077825

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8326e338d55b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('industry_area',
                  sa.Column('is_read_only', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('industry_area', 'is_read_only')
    # ### end Alembic commands ###
