"""empty message

Revision ID: d763ca605e4f
Revises: 
Create Date: 2019-11-30 12:38:32.796459

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd763ca605e4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alumnus_email_stat_alu_alumnus_id'), 'alumnus_email_stat', ['alu_alumnus_id'],
                    unique=False)
    op.create_index(op.f('ix_alumnus_email_stat_alu_status_id'), 'alumnus_email_stat', ['alu_status_id'], unique=False)
    op.create_index(op.f('ix_alumnus_email_stat_alu_user_id'), 'alumnus_email_stat', ['alu_user_id'], unique=False)
    op.create_index(op.f('ix_company_company_industry_id'), 'company', ['company_industry_id'], unique=False)
    op.create_index(op.f('ix_company_contact_employee_id'), 'company_contact', ['employee_id'], unique=False)
    op.create_index(op.f('ix_company_email_stat_comp_comp_id'), 'company_email_stat', ['comp_comp_id'], unique=False)
    op.create_index(op.f('ix_company_email_stat_comp_status_id'), 'company_email_stat', ['comp_status_id'],
                    unique=False)
    op.create_index(op.f('ix_company_email_stat_comp_user_id'), 'company_email_stat', ['comp_user_id'], unique=False)
    op.create_index(op.f('ix_employee_employee_current_company_Id'), 'employee', ['employee_current_company_Id'],
                    unique=False)
    op.create_index(op.f('ix_employee_employee_industry_id'), 'employee', ['employee_industry_id'], unique=False)
    op.create_index(op.f('ix_employee_company_company_id'), 'employee_company', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_user_handle_industry_id'), 'user', ['user_handle_industry_id'], unique=False)
    op.create_index(op.f('ix_user_user_role_id'), 'user', ['user_role_id'], unique=False)
    op.create_index(op.f('ix_user_report_design_user_id'), 'user_report_design', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_report_design_user_id'), table_name='user_report_design')
    op.drop_index(op.f('ix_user_user_role_id'), table_name='user')
    op.drop_index(op.f('ix_user_user_handle_industry_id'), table_name='user')
    op.drop_index(op.f('ix_employee_company_company_id'), table_name='employee_company')
    op.drop_index(op.f('ix_employee_employee_industry_id'), table_name='employee')
    op.drop_index(op.f('ix_employee_employee_current_company_Id'), table_name='employee')
    op.drop_index(op.f('ix_company_email_stat_comp_user_id'), table_name='company_email_stat')
    op.drop_index(op.f('ix_company_email_stat_comp_status_id'), table_name='company_email_stat')
    op.drop_index(op.f('ix_company_email_stat_comp_comp_id'), table_name='company_email_stat')
    op.drop_index(op.f('ix_company_contact_employee_id'), table_name='company_contact')
    op.drop_index(op.f('ix_company_company_industry_id'), table_name='company')
    op.drop_index(op.f('ix_alumnus_email_stat_alu_user_id'), table_name='alumnus_email_stat')
    op.drop_index(op.f('ix_alumnus_email_stat_alu_status_id'), table_name='alumnus_email_stat')
    op.drop_index(op.f('ix_alumnus_email_stat_alu_alumnus_id'), table_name='alumnus_email_stat')
    # ### end Alembic commands ###
